### ISSUE TITLE
Handle tracking in background while screen is turned off

### ISSUE THREAD

**Issue by florianschwanz** [florianschwanz/fom-big-data-bike-path-quality-android#9]
Tracking activity transition and sensor data should not require the screen to be turned on since this
* drains the battery
* exposes the risk of accidental inputs

Therefore all the tracking should be put in a background thread that runs even when the app is not active.
According to the [documentation](https://developer.android.com/guide/topics/sensors/sensors_overview) _The system will not disable sensors automatically when the screen turns off_.

#### Alarm manager

* https://developer.android.com/training/scheduling/alarms

#### Work manager

* https://medium.com/androiddevelopers/workmanager-periodicity-ff35185ff006
* https://developer.android.com/topic/libraries/architecture/workmanager?gclid=CjwKCAjwvMqDBhB8EiwA2iSmPDk3EhqBR0BhYk3xctsZV8WqWyU__cs6OUWihHY33kGzTSF2WnFvbxoC3mEQAvD_BwE&gclsrc=aw.ds

#### Foreground service

* https://developer.android.com/guide/components/foreground-services
* https://medium.com/@Lakshya_Punhani/background-services-running-forever-in-android-part-2-6e3a667d36fd

#### Wake lock

* https://developer.android.com/training/scheduling/wakelock
* https://stackoverflow.com/questions/9982433/android-accelerometer-not-working-when-screen-is-turned-off#

**Comment by florianschwanz** [comment]
Foreground service is the way to go, when inheriting from ```androidx.lifecycle.LifecycleService``` it can act as a lifecycle owner which can
* listen to live data, e.g. location, accelerometer
* interact with room databases

- [ ] A notification should show the user whether the tracking is active or inactive.
- [ ] Automatic tracking should interact seamlessly with manual start of a bike activity
* the user should be able to manually stop a bike activity that has been started automatically
* the user should be able to manually start a bike activity which potentially will be stopped by automatic detection
- [ ] Automatic tracking should work with
* app being active
* app being in pocket mode
* a mix of both
- [ ] There should be a way to activate / deactivate the service.
